package Class;

/**
*
* @author david
*/
public class Kitchenform1 extends javax.swing.JFrame {

    /** Creates new form Kitchenform1 */
    public Kitchenform1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        numbOfOrders = new javax.swing.JLabel();
        order1Lable = new javax.swing.JLabel();
        order2Lable = new javax.swing.JLabel();
        order3Lable = new javax.swing.JLabel();
        order4Lable = new javax.swing.JLabel();
        order5Lable = new javax.swing.JLabel();
        delivery1Lable = new javax.swing.JLabel();
        delivery2Lable = new javax.swing.JLabel();
        delivery3Lable = new javax.swing.JLabel();
        delivery4Lable = new javax.swing.JLabel();
        delivery5Lable = new javax.swing.JLabel();
        order1Button = new javax.swing.JButton();
        order2Button = new javax.swing.JButton();
        order3Button = new javax.swing.JButton();
        order4Button = new javax.swing.JButton();
        order5Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Kj¿kken");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(314, 314, 314)
                .add(jLabel1)
                .addContainerGap(343, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        backButton.setText("Tilbake");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("Antall ordre:");

        numbOfOrders.setFont(new java.awt.Font("Tahoma", 0, 24));
        numbOfOrders.setText("4");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(69, 69, 69)
                .add(backButton)
                .add(137, 137, 137)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(numbOfOrders)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(backButton)
                    .add(numbOfOrders)
                    .add(jLabel2))
                .add(32, 32, 32))
        );

        order1Lable.setText("Pizza #3 (3stk):");

        order2Lable.setText("Pizza #4 (1stk)");

        order3Lable.setText("Pizza #1 (5stk)");

        order4Lable.setText("Pizza #6 (3stk)");

        order5Lable.setText("Pizza #1 (1stk)");

        delivery1Lable.setText("19:25");

        delivery2Lable.setText("20:02");

        delivery3Lable.setText("20:25");

        delivery4Lable.setText("21:30");

        delivery5Lable.setText("22:22");

        order1Button.setText("Ordre #1");

        order2Button.setText("Ordre #2");

        order3Button.setText("Ordre #3");

        order4Button.setText("Ordre #4");

        order5Button.setText("Ordre #5");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(152, 152, 152)
                .add(order1Lable)
                .add(76, 76, 76)
                .add(delivery1Lable)
                .add(135, 135, 135)
                .add(order1Button))
            .add(layout.createSequentialGroup()
                .add(152, 152, 152)
                .add(order2Lable)
                .add(80, 80, 80)
                .add(delivery2Lable)
                .add(135, 135, 135)
                .add(order2Button))
            .add(layout.createSequentialGroup()
                .add(152, 152, 152)
                .add(order3Lable)
                .add(80, 80, 80)
                .add(delivery3Lable)
                .add(135, 135, 135)
                .add(order3Button))
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(152, 152, 152)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(order4Lable)
                        .add(80, 80, 80)
                        .add(delivery4Lable))
                    .add(layout.createSequentialGroup()
                        .add(order5Lable)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(delivery5Lable)))
                .add(135, 135, 135)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(order4Button)
                    .add(order5Button))
                .add(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(72, 72, 72)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(order1Lable))
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(delivery1Lable))
                    .add(order1Button))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(order2Lable))
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(delivery2Lable))
                    .add(order2Button))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(order3Lable))
                    .add(delivery3Lable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(order3Button))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(order4Lable)
                    .add(delivery4Lable)
                    .add(order4Button))
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(8, 8, 8)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(order5Lable)
                            .add(delivery5Lable)))
                    .add(layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(order5Button)))
                .add(64, 64, 64)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitchenform1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitchenform1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitchenform1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitchenform1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Kitchenform1().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton backButton;
    private javax.swing.JLabel delivery1Lable;
    private javax.swing.JLabel delivery2Lable;
    private javax.swing.JLabel delivery3Lable;
    private javax.swing.JLabel delivery4Lable;
    private javax.swing.JLabel delivery5Lable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numbOfOrders;
    private javax.swing.JButton order1Button;
    private javax.swing.JLabel order1Lable;
    private javax.swing.JButton order2Button;
    private javax.swing.JLabel order2Lable;
    private javax.swing.JButton order3Button;
    private javax.swing.JLabel order3Lable;
    private javax.swing.JButton order4Button;
    private javax.swing.JLabel order4Lable;
    private javax.swing.JButton order5Button;
    private javax.swing.JLabel order5Lable;
    // End of variables declaration                   
}