package Class;
//no.ntnu.course
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewOrder2Form.java
 *
 * Created on 29.sep.2011, 12:24:07
 */
/**
 *
 * @author ole
 */
public class NewOrder2Form extends javax.swing.JFrame {

    /** Creates new form NewOrder2Form */
    public NewOrder2Form() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newOrderLabel = new javax.swing.JLabel();
        productBari = new javax.swing.JButton();
        productGenoa = new javax.swing.JButton();
        productCocacola = new javax.swing.JButton();
        productWater = new javax.swing.JButton();
        bariCounter = new javax.swing.JLabel();
        genoaCounter = new javax.swing.JLabel();
        waterCounter = new javax.swing.JLabel();
        CocacolaCounter = new javax.swing.JLabel();
        productSourCream = new javax.swing.JButton();
        sourCreamCounter = new javax.swing.JLabel();
        productGarlic = new javax.swing.JButton();
        garlicCounter = new javax.swing.JLabel();
        sendButton = new javax.swing.JButton();
        backButon = new javax.swing.JButton();
        totalPriceLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newOrderLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        newOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newOrderLabel.setText("NY ORDRE");

        productBari.setText("PIZZA BARI");
        productBari.setPreferredSize(new java.awt.Dimension(100, 23));

        productGenoa.setText("PIZZA GENOA");
        productGenoa.setPreferredSize(new java.awt.Dimension(100, 23));

        productCocacola.setText("COCA-COLA");
        productCocacola.setPreferredSize(new java.awt.Dimension(100, 23));

        productWater.setText("VANN");
        productWater.setPreferredSize(new java.awt.Dimension(100, 23));

        bariCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        bariCounter.setText("0");

        genoaCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        genoaCounter.setText("0");

        waterCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        waterCounter.setText("0");

        CocacolaCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        CocacolaCounter.setText("0");

        productSourCream.setText("RØMME");
        productSourCream.setPreferredSize(new java.awt.Dimension(100, 23));

        sourCreamCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        sourCreamCounter.setText("0");

        productGarlic.setText("HVITLØK");
        productGarlic.setPreferredSize(new java.awt.Dimension(100, 23));

        garlicCounter.setFont(new java.awt.Font("Tahoma", 1, 14));
        garlicCounter.setText("0");

        sendButton.setText("Fullfør");

        backButon.setText("Tilbake");

        totalPriceLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalPriceLabel.setText("Pris: 1337.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(newOrderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                .addGap(209, 209, 209))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productBari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bariCounter)
                        .addGap(86, 86, 86)
                        .addComponent(productGenoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genoaCounter)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(backButon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CocacolaCounter))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productSourCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sourCreamCounter)))
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(waterCounter))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(productGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(garlicCounter)))
                                .addGap(83, 83, 83)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalPriceLabel)
                        .addGap(249, 249, 249)
                        .addComponent(sendButton)
                        .addGap(176, 176, 176))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(newOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productBari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bariCounter)
                    .addComponent(productGenoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genoaCounter))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productCocacola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CocacolaCounter)
                    .addComponent(productWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(waterCounter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productSourCream, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourCreamCounter)
                    .addComponent(productGarlic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(garlicCounter))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButon)
                    .addComponent(sendButton)
                    .addComponent(totalPriceLabel))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewOrder2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewOrder2Form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CocacolaCounter;
    private javax.swing.JButton backButon;
    private javax.swing.JLabel bariCounter;
    private javax.swing.JLabel garlicCounter;
    private javax.swing.JLabel genoaCounter;
    private javax.swing.JLabel newOrderLabel;
    private javax.swing.JButton productBari;
    private javax.swing.JButton productCocacola;
    private javax.swing.JButton productGarlic;
    private javax.swing.JButton productGenoa;
    private javax.swing.JButton productSourCream;
    private javax.swing.JButton productWater;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel sourCreamCounter;
    private javax.swing.JLabel totalPriceLabel;
    private javax.swing.JLabel waterCounter;
    // End of variables declaration//GEN-END:variables
}
